app-template:
  controllers:
    tautulli:
      containers:
        app:
          image:
            repository: lscr.io/linuxserver/tautulli
            tag: v2.17.1-ls232@sha256:8e1a0d8104422f646c3e89d9b261b0507dc664bd6764baaea0ff0a5718f83b94
          env:
            TZ: Europe/Brussels
            PUID: "3001"
            PGID: "3001"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
              spec:
                failureThreshold: 30
                periodSeconds: 5
  
  service:
    app:
      controller: tautulli
      ports:
        http:
          port: 8181
  
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      storageClass: nfs-config
      accessMode: ReadWriteOnce
      size: 1Gi
