apiVersion: v2
name: authentik-umbrella
description: Authentik identity provider with HTTPRoute for internal access
type: application
version: 1.0.0
appVersion: "2026.5.2"

dependencies:
  - name: authentik
    version: 2026.8.1
    repository: https://charts.goauthentik.io
